default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    prepared_statements: true
    sslmode: <%= ENV['DB_SSL_MODE'] || 'prefer' %>

  # Solid Queue requires this separate database
  queue:
    <<: *default
    url: <%= ENV['SOLID_QUEUE_DATABASE_URL'] || "postgresql://postgres:#{ENV.fetch('DB_PASSWORD')}@postgres:5432/solid_queue_#{Rails.env}" %>
    migrations_paths: db/solid_queue_migrate
